 spring:
  application:
   name: Car Service
  datasource:
   url: jdbc:mysql://localhost:3308/carservice
   username: root
   password: stars19
   driver-class-name: com.mysql.cj.jdbc.Driver
 
  jpa:
   generate-ddl: false
   show-sql: false
   hibernate:
    ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
   enabled: true
   url: jdbc:mysql://localhost:3308/carservice
   user: root
   password: stars19
   locations: classpath:db/migration
    
 server:
  port : 0